version: "3.9"

services:
  app:
    build: .
    container_name: devices-security-lab-v2
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: devices-security-lab-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: devices_security_lab_v2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
